console.log("welcome to TS...!");
var a;
a = 10;
var b = 20;
var c = a + b;
console.log(c);
var kiran;
kiran = "this is static value";
console.log(kiran);
var gokul;
gokul = "this is const value";
console.log(gokul);
var decimal = 6;
console.log("Decimal Value is:" + decimal);
var hex = 0xf00d;
console.log("Hex value is:" + hex);
var binary = 10;
console.log("Binary value is :" + binary);
var octal = 484;
console.log("Octal value is :" + octal);
var color = "blue";
console.log("color value is color :" + color);
color = "blue";
console.log("color value is color :" + color);
var fullName = "Punith";
console.log("Full name value is :" + fullName);
var age = 37;
console.log("age is:" + age);
var sentence1 = "Hello my name is" + fullName + "./n/n" +
    "I'll be" + (age + 1) + "years old next month.";
console.log(sentence1);
var list = [1, 2, 3];
console.log("List ARRAY VALue is:" + list);
//the second way uses a generic array type,Array<DataType>:
var list1 = [1, 2, 3];
console.log("List1 array value is:" + list1);
var unionVariable;
unionVariable = 200;
console.log("unionVariable value is:" + unionVariable);
unionVariable = "Typescript 1.4 gives program the ability to combine one or more data or one or more datatype";
console.log("unionVariable value is:" + unionVariable);
